#!/bin/sh
set -eu
case "$(uname -s):$(uname -m)" in
    Darwin:x86_64) printf '%s\n' x86_64-macos ;;
    Darwin:arm64) printf '%s\n' arm64-macos ;;
    Linux:x86_64) printf '%s\n' x86_64-linux ;;
    Linux:aarch64) printf '%s\n' arm64-linux ;;
    *) printf '%s\n' 'error: Crown requires a 64-bit ARM or x86 macOS or Linux host' >&2; exit 1 ;;
esac
